In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('architecture.csv')
df

,institute_id,name,"tlr (Teaching, Learning & Resources)",rpc (Research and Professional Practice),go (Graduation Outcomes),oi (Outreach and Inclusivity),perception(Peer Perception),city,state,NIRF rank
0,IR-A-U-0573,Indian Institute of Technology Kharagpur,81.72,93.02,93.38,74.46,75.00,Kharagpur,West Bengal,1
1,IR-A-U-0560,Indian Institute of Technology Roorkee,81.32,85.34,87.15,70.90,56.30,Roorkee,Uttarakhand,2
2,IR-A-U-0263,National Institute of Technology Calicut,89.70,27.93,75.96,66.96,58.79,Kozhikode,Kerala,3
3,IR-A-U-0127,Centre for Environmental Planning and Technolo...,70.14,43.18,82.53,59.98,74.72,Ahmedabad,Gujarat,4
4,IR-A-U-0116,School of Planning and Architecture,74.58,20.51,73.47,70.15,100.00,New Delhi,Delhi,5
5,IR-A-U-0584,Indian Institute of Engineering Science and Te...,71.68,62.31,74.67,52.88,37.00,Shibpur,West Bengal,6
6,IR-A-U-0626,School of Planning and Architecture,79.91,22.57,74.12,73.51,52.25,Bhopal,Madhya Pradesh,7
7,IR-A-U-0467,National Institute of Technology Tiruchirappalli,49.63,52.10,83.90,59.37,73.03,Tiruchirappalli,Tamil Nadu,8
8,IR-A-U-0627,School of Planning and Architecture,74.20,5.20,82.32,68.21,56.30,Vijayawada,Andhra Pradesh,9
9,IR-A-U-0108,Jamia Millia Islamia,66.06,0.67,87.09,78.60,44.47,New Delhi,Delhi,10
10,IR-A-C-43708,College of Engineering Trivandrum,57.69,25.46,92.24,54.30,37.00,Thiruvananthapuram,Kerala,11
11,IR-A-C-46330,Manipal Academy of Higher Education,61.52,0.00,79.85,70.35,54.99,Udupi,Karnataka,12
12,IR-A-U-0202,Birla Institute of Technology,51.76,40.71,60.95,60.59,53.64,Ranchi,Jharkhand,13
13,IR-A-C-57952,BMS College of Arhitecture,63.40,0.01,77.67,57.88,54.99,Bengaluru,Karnataka,14
14,IR-A-U-0284,Maulana Azad National Institute of Technology,56.44,34.30,71.03,55.22,25.28,Bhopal,Madhya Pradesh,15
15,IR-A-U-0496,Aligarh Muslim University,40.68,50.18,88.25,40.73,34.91,Aligarh,Uttar Pradesh,16
16,IR-A-C-26794,Thiagarajar College of Engineering,47.68,24.60,78.55,51.00,54.99,Madurai,Tamil Nadu,17
17,IR-A-U-0439,Anna University,46.60,25.50,58.10,52.83,80.87,Chennai,Tamil Nadu,18
18,IR-A-U-0189,National Institute of Technology Hamirpur,44.44,51.07,59.84,58.42,27.90,Hamirpur,Himachal Pradesh,19
19,IR-A-U-0454,Hindustan Institute of Technology and Science...,53.75,19.68,80.14,47.84,22.48,Chennai,Tamil Nadu,20

In [ ]:
%%sql